{
  "id": "ch_C0516UPPMT3_2023-09-21_1695281334.489099_thread",
  "type": "channel",
  "channel_name": "aihub-feedback",
  "conversation_type": "thread",
  "participants": [
    "Kerry",
    "Hari",
    "Sławek Biel",
    "Timo Meijrink",
    "Varun Jain"
  ],
  "messages": [
    {
      "sender": "Timo Meijrink",
      "user_id": "U02GCQ0JLUC",
      "message": "On aihub-sandbox.internal.instabase.com (http://aihub-sandbox.internal.instabase.com) when I upload the attached document and ask the following question, I get the attached error\nPrompt: \"Extract the table with the items shipped\"",
      "time": "00:28",
      "timestamp": "1695281334.489099",
      "is_reply": false
    },
    {
      "sender": "Timo Meijrink",
      "user_id": "U02GCQ0JLUC",
      "message": "I get the error on every prompt, just a different number in the error.",
      "time": "00:30",
      "timestamp": "1695281420.952699",
      "is_reply": true
    },
    {
      "sender": "Sławek Biel",
      "user_id": "U03E1LBTKV2",
      "message": "Yes, I see the same bug, reported it here: https://instabase.slack.com/archives/C05AEKWJKPT/p1695280555278559?thread_ts=1695194580.938859&cid=C05AEKWJKPT\n\nIt fails on saving the token usage stats",
      "time": "00:47",
      "timestamp": "1695282456.259739",
      "is_reply": true
    },
    {
      "sender": "Varun Jain",
      "user_id": "U019KDMQL14",
      "message": "@Rakesh @Hari - who can help look into this?",
      "time": "00:48",
      "timestamp": "1695282494.587569",
      "is_reply": true
    },
    {
      "sender": "Sławek Biel",
      "user_id": "U03E1LBTKV2",
      "message": "It’s probably related to the changes @mfichman was doing yesterday",
      "time": "00:49",
      "timestamp": "1695282542.299849",
      "is_reply": true
    },
    {
      "sender": "Hari",
      "user_id": "UCX3XL72Q",
      "message": "Internal Sandbox is bound to have some intermittent issues, it’s the eng dogfood. @Timo Meijrink Can you use UAT until this is fixed?",
      "time": "00:51",
      "timestamp": "1695282695.215419",
      "is_reply": true
    },
    {
      "sender": "Timo Meijrink",
      "user_id": "U02GCQ0JLUC",
      "message": "Yes, sorry for not giving the context, I was just playing around, no blockers...",
      "time": "00:54",
      "timestamp": "1695282842.334269",
      "is_reply": true
    },
    {
      "sender": "Hari",
      "user_id": "UCX3XL72Q",
      "message": "Thanks!! We will update here once it's fixed!",
      "time": "00:54",
      "timestamp": "1695282897.866249",
      "is_reply": true
    },
    {
      "sender": "Varun Jain",
      "user_id": "U019KDMQL14",
      "message": "@Kerry this is a thread on the bug due to which sandbox has been broken for the full day.",
      "time": "08:40",
      "timestamp": "1695310828.436839",
      "is_reply": true
    },
    {
      "sender": "Kerry",
      "user_id": "UCX3VGDJR",
      "message": ":+1: sandbox is quite broken now after yesterday's maintenance, i'm following up in the eng-aihub channel",
      "time": "08:41",
      "timestamp": "1695310884.051209",
      "is_reply": true
    }
  ],
  "metadata": {
    "channel_id": "C0516UPPMT3",
    "channel_name": "aihub-feedback",
    "date_file": "2023-09-21.json",
    "message_count": 10,
    "start_time": "1695281334.489099",
    "end_time": "1695310884.051209",
    "is_thread": true
  }
}