{
  "id": "ch_CSY11CK7T_2025-01-13_1736792389.091329_thread",
  "type": "channel",
  "channel_name": "discuss-frontend",
  "conversation_type": "thread",
  "participants": [
    "danny.lan",
    "Udit",
    "jordy.vlan",
    "Nikolaos Kofinas",
    "Serena",
    "lydia"
  ],
  "messages": [
    {
      "sender": "danny.lan",
      "user_id": "U03R26W3CDU",
      "message": "*Cypress on call update (Jan 6 week)*:cypress-spin: \n• `run-app`, `run-public-app` Seeing a failure running the app similar to this previous error (https://instabase.slack.com/archives/C05EQQJGN7L/p1720630631397669) where classification fails and the error is `No input given to obtain a ParsedIBOCR`. @jordy.vlan do you know what might be happening here? Here are the logs (https://aihub-sandbox.internal.instabase.com/deployment-manager/logs?deployments=model-service&start_time=1736779821000000000&end_time=1736779822000000000)\n• `downstream-integrations` button is not visible on screen. Will push fix\n• `documents-grid, field-editor, file-list, nested-field-editor, results-table`  loading an app takes a long time because each time the tests run, it creates a new version, and now there are almost 1000 app versions which get fetched every time the app is opened :grimacing: \n    ◦ I’ll manually set old versions as INACTIVE and try and add a step to the test to mark old versions as inactive when creating a new version\nOn the CI side, cypress didn’t seem too flaky this week!",
      "time": "10:19",
      "timestamp": "1736792389.091329",
      "is_reply": false
    },
    {
      "sender": "Udit",
      "user_id": "U03M519DVKR",
      "message": "wait why do the human review ones create a new version? They run the same app that exists. Unless someone has changed them.",
      "time": "10:37",
      "timestamp": "1736793454.665909",
      "is_reply": true
    },
    {
      "sender": "danny.lan",
      "user_id": "U03R26W3CDU",
      "message": "Oh I see, I think just going to the app page causes the fetch for a different app (`cypress-edit-app`)\n\nIt’s a separate test that is creating the versions, but having so many versions affects a bunch of tests that go through the app page",
      "time": "10:41",
      "timestamp": "1736793679.174799",
      "is_reply": true
    },
    {
      "sender": "Udit",
      "user_id": "U03M519DVKR",
      "message": "yah, that makes sense",
      "time": "10:43",
      "timestamp": "1736793785.779589",
      "is_reply": true
    },
    {
      "sender": "Udit",
      "user_id": "U03M519DVKR",
      "message": "I could avoid the app page, but because of diff environments I would need the app id for each environment saved which I don't love",
      "time": "10:43",
      "timestamp": "1736793816.533839",
      "is_reply": true
    },
    {
      "sender": "danny.lan",
      "user_id": "U03R26W3CDU",
      "message": "yeah i think the human review tests are fine, I’ll add a step in the `create-delete-app` test to mark previous versions as inactive which should fix the issue",
      "time": "10:44",
      "timestamp": "1736793888.737299",
      "is_reply": true
    },
    {
      "sender": "Udit",
      "user_id": "U03M519DVKR",
      "message": "some of them are definitely skipped right now which I need to fix and unskip :pray:",
      "time": "10:45",
      "timestamp": "1736793954.688219",
      "is_reply": true
    },
    {
      "sender": "Serena",
      "user_id": "U01CZ3LBFU4",
      "message": "@danny.lan the link for `this previous error` in the first bullet doesn’t work for me?",
      "time": "11:24",
      "timestamp": "1736796283.209209",
      "is_reply": true
    },
    {
      "sender": "danny.lan",
      "user_id": "U03R26W3CDU",
      "message": "oops fixed it!",
      "time": "11:26",
      "timestamp": "1736796371.571019",
      "is_reply": true
    },
    {
      "sender": "Serena",
      "user_id": "U01CZ3LBFU4",
      "message": "cc @Nikolaos Kofinas for the first bullet since he made recent changes to classification",
      "time": "12:32",
      "timestamp": "1736800379.606899",
      "is_reply": true
    },
    {
      "sender": "Serena",
      "user_id": "U01CZ3LBFU4",
      "message": "@Nikolaos Kofinas it seems that https://github.com/instabase/instabase/pull/66521/files#diff-0f82f4cab0ec70949a6aed7ec56f79a0b70bb9e77c46de9b7f2d8a743a831821R64 changed the classification task to use `create_document_from_request`, instead of `resolve_text_from_request`, which breaks the running of old apps\n\nsee explanation linked by Danny in his first bullet\n\ncc @lydia",
      "time": "12:33",
      "timestamp": "1736800422.862269",
      "is_reply": true
    },
    {
      "sender": "lydia",
      "user_id": "UJK4LKYSJ",
      "message": "@Serena do you have a link to the app? do all apps fail? or just certain apps?",
      "time": "12:41",
      "timestamp": "1736800882.631759",
      "is_reply": true
    },
    {
      "sender": "lydia",
      "user_id": "UJK4LKYSJ",
      "message": "nvm I see that info in the follow-up thread",
      "time": "12:44",
      "timestamp": "1736801095.396409",
      "is_reply": true
    },
    {
      "sender": "lydia",
      "user_id": "UJK4LKYSJ",
      "message": "@jordy.vlan can you help fix this during your day tomorrow? How did you fix it for your previous PR? I know @Nikolaos Kofinas is deep in mypy fixes at the moment.",
      "time": "12:45",
      "timestamp": "1736801125.156959",
      "is_reply": true
    },
    {
      "sender": "lydia",
      "user_id": "UJK4LKYSJ",
      "message": "@danny.lan is the current error message still `No input given to obtain a ParsedIBOCR` in model-service? I'm not seeing this error message on prod in the past 2 days, so perhaps not too many customers will run into this issue",
      "time": "12:46",
      "timestamp": "1736801165.205039",
      "is_reply": true
    },
    {
      "sender": "Serena",
      "user_id": "U01CZ3LBFU4",
      "message": "this should only happen in 25.02, not 24.50\n\nso this shouldn’t happen on prod",
      "time": "12:46",
      "timestamp": "1736801203.409769",
      "is_reply": true
    },
    {
      "sender": "lydia",
      "user_id": "UJK4LKYSJ",
      "message": "Nikolaos's PR was backported to 24.48 and 24.50, so it should have gone out in the weekly patch",
      "time": "12:47",
      "timestamp": "1736801233.204529",
      "is_reply": true
    },
    {
      "sender": "Serena",
      "user_id": "U01CZ3LBFU4",
      "message": "nvm i see :disappointed:",
      "time": "12:47",
      "timestamp": "1736801238.854479",
      "is_reply": true
    },
    {
      "sender": "Nikolaos Kofinas",
      "user_id": "U03DWCUEBHT",
      "message": "hmmm do we now why this is failingV what was different on old apps? because basically we do the same thing with extra steps with the document.py",
      "time": "12:49",
      "timestamp": "1736801348.596189",
      "is_reply": true
    },
    {
      "sender": "Nikolaos Kofinas",
      "user_id": "U03DWCUEBHT",
      "message": "and why it doesn't fail on prod?",
      "time": "12:49",
      "timestamp": "1736801362.745869",
      "is_reply": true
    },
    {
      "sender": "Nikolaos Kofinas",
      "user_id": "U03DWCUEBHT",
      "message": "(on 25.02)",
      "time": "12:49",
      "timestamp": "1736801371.686089",
      "is_reply": true
    },
    {
      "sender": "lydia",
      "user_id": "UJK4LKYSJ",
      "message": "@danny.lan can you link the failed cypress run? would make debugging easier :smile:",
      "time": "12:50",
      "timestamp": "1736801425.568099",
      "is_reply": true
    },
    {
      "sender": "lydia",
      "user_id": "UJK4LKYSJ",
      "message": "oh nvm, i see the model-service logs linked. trace id: 12b0a138284892c5",
      "time": "12:51",
      "timestamp": "1736801482.849219",
      "is_reply": true
    },
    {
      "sender": "danny.lan",
      "user_id": "U03R26W3CDU",
      "message": "here’s the latest cypress run on master fyi, it failed in this run too https://cloud.cypress.io/projects/cfhedy/runs/16708/test-results/d91b12c1-336c-48ce-a[…]31%5C%22%5D%22%7D%5D&statuses=%5B%5D&testingTypesEnum=%5B%5D (https://cloud.cypress.io/projects/cfhedy/runs/16708/test-results/d91b12c1-336c-48ce-ab43-a85f4def6ed0?actions=%5B%5D&browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%7B%22label%22%3A%22apps%2Fsrc%2Faihub%2F__e2e__%2FViewApp%2Frun-public-app.spec.ts%22%2C%22value%22%3A%22%5B%5C%22904a3513-b177-4e08-97e8-fb5a94264579%5C%22%5D%22%7D%2C%7B%22label%22%3A%22apps%2Fsrc%2Faihub%2F__e2e__%2FViewApp%2Frun-app.spec.ts%22%2C%22value%22%3A%22%5B%5C%220b130e3a-f17a-4205-9d2f-f3bc4f1a1131%5C%22%5D%22%7D%5D&statuses=%5B%5D&testingTypesEnum=%5B%5D)",
      "time": "12:51",
      "timestamp": "1736801510.997659",
      "is_reply": true
    },
    {
      "sender": "lydia",
      "user_id": "UJK4LKYSJ",
      "message": "ok! Found the app that failed, and this is the custom_classifier.py script:\n```import logging\nfrom typing import Optional, Tuple, Union, Text\n\nfrom google.protobuf import struct_pb2\nfrom google.protobuf import json_format\nfrom instabase.model_utils.classifier import (\n    ClassifierInput,\n    DocumentSplitResult,\n)\nfrom instabase.ocr.client.libs.ibocr import ParsedIBOCR\nfrom instabase.protos.model_service import model_service_pb2\nfrom instabase.utils.path import ibpath\nfrom instabase.model_utils.classifier_connectors import (\n    ClassifierModelServiceConnector,\n    make_register_classifiers_fn,\n)\nfrom instabase.metrics_utils.metric_constants import UNKNOWN_ATTRIBUTE_VALUE, APP_SOURCE_TYPE\n\n\ndef _ibocr_to_text(\n    ibocr: ParsedIBOCR\n) -> Tuple[Optional[Text], Optional[Text]]:  # extract text from an IBOCR\n  '''\n  Transform an IBOCR file in Python representation into a string containing\n  the concatenation of each page.\n  '''\n  page_texts = []\n  for i in range(ibocr.get_num_records()):\n    cur_txt, err = ibocr.get_text_at_record(i)\n    if err:\n      return None, err\n    page_texts.append(cur_txt)\n\n  return '\\\\n'.join(page_texts), None\n\n\nclass ModelWrapper(ClassifierModelServiceConnector):\n  model_name = 'ibllm'\n  model_version = '2.1.0'\n  use_parsed_ibocr = False\n\n  def inner_predict(\n      self, datapoint: ParsedIBOCR\n  ) -> Tuple[Optional[DocumentSplitResult], Optional[str]]:\n    return None, None\n\n  def get_text(self, datapoint: ClassifierInput) -> Optional[str]:\n    text = datapoint.get_text()\n    if text:\n      return text\n    if datapoint.get_ibocr():\n      text_content, ibocr_error = _ibocr_to_text(datapoint.get_ibocr())\n      if not ibocr_error:\n        return text_content\n      raise ValueError(\"Could not get text from the document\")\n    return None\n\n  def _make_ms_request(\n      self, classifier_type: str, datapoint: ClassifierInput\n  ) -> Union[Tuple[bytes, str], Tuple[bytes, Optional[str], str]]:\n    '''Forwards the input filepath to the corresponding Model Service model.\n    Return a tuple of three elements, when the model inference result\n    contains a type indicating the class score is also returned\n    '''\n    try:\n      from instabase.model_service.sdk import ModelService, get_model_client  # type: ignore\n    except ImportError:\n      return b'', 'Model Service SDK unavailable.'\n\n    fn_ctx = datapoint.get_fn_ctx()\n    if fn_ctx is None:\n      return b'', 'datapoint fn_ctx is None'\n\n    clients, err = fn_ctx.get_by_col_name('CLIENTS')\n    username = (clients.ibfile._get_username()\n                )  # hacky way to get username since fn_ctx has no client\n\n    root_output_folder, err = fn_ctx.get_by_col_name('ROOT_OUTPUT_FOLDER')\n    if err:\n      return b'', 'No root output folder filepath for associated fn_ctx'\n\n    runtime_config, err = fn_ctx.get_by_col_name(\"CONFIG\")\n    if err:\n      raise KeyError(err)\n    app_id = runtime_config.get('app_id', UNKNOWN_ATTRIBUTE_VALUE)\n    # Making sure result cache folder is root directory.\n    result_cache_folder = root_output_folder\n    # Since root_output_folder is path to step output folder for classifiers and\n    # we need root folder to store cache in model-service.So change cache folder\n    # to out_dir only if root_output_folder is not None and is a step_folder.\n    if root_output_folder:\n      out_dir, _ = ibpath.split_file(root_output_folder)\n      if out_dir:\n        result_cache_folder = out_dir\n\n    custom_request = struct_pb2.Struct()\n    # flake8: noqa\n    custom_request.update({  # type: ignore\n        'classifier_type': classifier_type,\n        'classes': ['W2', 'Other', 'Vehicle Document', 'Passport'],  # type: ignore\n        'task': 'classification',\n        'source_type': APP_SOURCE_TYPE,\n        'source_id': app_id\n    })\n\n    job_id, err = fn_ctx.get_by_col_name('JOB_ID')\n    if err:\n      logging.warning('JOB_ID not found. Sending None value to Model Service.')\n\n    ms = ModelService(\n        username=username,\n        model_client=get_model_client(use_model_service_lite=True))\n\n    # Project model compatible classifier module has model information\n    # written in the .ibclassifier and set in fn_ctx. Attempt to\n    # read the model information from fx_ctx first.\n    is_project_model: bool = False\n    model_fs_path: Optional[str] = None\n    model_version = self._model_version or None\n    model_name = self._model_name\n\n    req = model_service_pb2.RunModelRequest(\n        context=ms._get_context(),\n        result_cache_folder=result_cache_folder,\n        model_service_context=model_service_pb2.ModelServiceContext(\n            model_paths=[self._model_path] if self._model_path else None, ),\n        input_string=self.get_text(datapoint),\n        model_name=model_name,\n        model_version=model_version,\n        model_fs_path=model_fs_path,\n        is_project_model=is_project_model,\n        model_payload=model_service_pb2.ModelPayload(\n            custom_request=custom_request, ),\n        job_id=job_id,\n    )\n\n    result = ms.run(req)\n\n    if not result.HasField('model_result'):\n      return b'', 'Expected model_result in RunModelResponse.'\n\n    json_result = json_format.MessageToDict(result)\n\n    if \"customResult\" in json_result[\"modelResult\"]:\n      custom_result = json_result[\"modelResult\"][\"customResult\"]\n      error = custom_result[\"error\"]\n      if error:\n        return b'', error\n      return custom_result[\"class_name\"].encode(\"utf-8\"), ''\n\n    if not result.model_result.HasField('raw_data'):\n      return b'', 'Expected raw_data in ModelResult.'\n\n    if not result.model_result.raw_data.HasField('data'):\n      return b'', 'Expected data in RawData message.'\n\n    if result.model_result.raw_data.HasField(\n        'type') and result.model_result.raw_data.type == 'json':\n      # Return an additional element only when the `raw_data.type` is json.\n      # This is a case where a classifier outputs confidence score beside\n      # class label in its prediction. We do not change the return format\n      # for other cases for backward compatibility reasons. Certain legacy\n      # classifiers/split classifiers in production have defined\n      # methods to make direct calls to this method and are unable to process\n      # the results if the return format of this method changes.\n      return result.model_result.raw_data.data, result.model_result.raw_data.type, ''\n    else:\n      return result.model_result.raw_data.data, ''\n\n\nregister_classifiers = make_register_classifiers_fn(ModelWrapper)```",
      "time": "13:08",
      "timestamp": "1736802517.937469",
      "is_reply": true
    },
    {
      "sender": "lydia",
      "user_id": "UJK4LKYSJ",
      "message": "This would apply to an app created before Vishnu's PR: https://github.com/instabase/instabase/pull/52504/",
      "time": "13:11",
      "timestamp": "1736802661.509089",
      "is_reply": true
    },
    {
      "sender": "lydia",
      "user_id": "UJK4LKYSJ",
      "message": "Cross-posting here since I realized I posted on the old thread\nhttps://instabase.slack.com/archives/C05EQQJGN7L/p1736803505275819?thread_ts=1720630631.397669&cid=C05EQQJGN7L\n\nSince users haven't hit this issue on prod yet, I think we can wait until the next maintenance cycle to ship the fix.",
      "time": "13:29",
      "timestamp": "1736803747.507969",
      "is_reply": true
    },
    {
      "sender": "lydia",
      "user_id": "UJK4LKYSJ",
      "message": "@danny.lan follow-up on the Cypress failures - do you know when we started hitting it last week? I'm wondering if we could have caught this before the prod push :disappointed:",
      "time": "13:29",
      "timestamp": "1736803797.330979",
      "is_reply": true
    },
    {
      "sender": "Nikolaos Kofinas",
      "user_id": "U03DWCUEBHT",
      "message": "yes we can revert this change, I didnt know about these custom scripts taht call ibllm differently",
      "time": "13:30",
      "timestamp": "1736803825.132609",
      "is_reply": true
    },
    {
      "sender": "lydia",
      "user_id": "UJK4LKYSJ",
      "message": "It looks like the PR was merged Jan 6 at 2pm ET. Ideally we could of caught it before the certification :disappointed:",
      "time": "13:31",
      "timestamp": "1736803872.353099",
      "is_reply": true
    },
    {
      "sender": "Nikolaos Kofinas",
      "user_id": "U03DWCUEBHT",
      "message": "can someone else do this reversion? I am kinda swamp right now",
      "time": "13:32",
      "timestamp": "1736803958.990009",
      "is_reply": true
    },
    {
      "sender": "lydia",
      "user_id": "UJK4LKYSJ",
      "message": "@jordy.vlan can you help with this tomorrow? thanks!",
      "time": "13:32",
      "timestamp": "1736803979.071639",
      "is_reply": true
    },
    {
      "sender": "lydia",
      "user_id": "UJK4LKYSJ",
      "message": "don't revert the entire PR - just the line I screenshot above",
      "time": "13:33",
      "timestamp": "1736804002.730269",
      "is_reply": true
    },
    {
      "sender": "Nikolaos Kofinas",
      "user_id": "U03DWCUEBHT",
      "message": "I can do this from the online editor so give me 5 min",
      "time": "13:34",
      "timestamp": "1736804078.365709",
      "is_reply": true
    },
    {
      "sender": "lydia",
      "user_id": "UJK4LKYSJ",
      "message": "It's more the testing locally that'll take time. The code change is simple :smile: but we should test that the original issue is still fixed, and that old apps run.",
      "time": "13:35",
      "timestamp": "1736804140.409739",
      "is_reply": true
    },
    {
      "sender": "Nikolaos Kofinas",
      "user_id": "U03DWCUEBHT",
      "message": "yes also need to fix the tests, If I dont post a PR here by EOD please take a look @jordy.vlan",
      "time": "13:36",
      "timestamp": "1736804218.365369",
      "is_reply": true
    },
    {
      "sender": "jordy.vlan",
      "user_id": "U072CDMB4N8",
      "message": "Thanks for the updates, I will look into this tomorrow :smiley:",
      "time": "13:48",
      "timestamp": "1736804900.607289",
      "is_reply": true
    },
    {
      "sender": "Nikolaos Kofinas",
      "user_id": "U03DWCUEBHT",
      "message": "created the PR: https://github.com/instabase/instabase/pull/66948 please cross the finish line tomorrow jordy",
      "time": "16:42",
      "timestamp": "1736815333.204709",
      "is_reply": true
    }
  ],
  "metadata": {
    "channel_id": "CSY11CK7T",
    "channel_name": "discuss-frontend",
    "date_file": "2025-01-13.json",
    "message_count": 38,
    "start_time": "1736792389.091329",
    "end_time": "1736815333.204709",
    "is_thread": true
  }
}