{
  "id": "ch_CSY11CK7T_2024-09-16_1726512027.180189_thread",
  "type": "channel",
  "channel_name": "discuss-frontend",
  "conversation_type": "thread",
  "participants": [
    "Serena",
    "danny.lan"
  ],
  "messages": [
    {
      "sender": "Serena",
      "user_id": "U01CZ3LBFU4",
      "message": "i know `aihub-derived-field` is a non-blocking test, but fyi it failed in my CI run (https://cloud.cypress.io/projects/cfhedy/runs/13892/overview/19bb831c-bb8c-49c9-9df2-e81b663973a8?roarHideRunsWithDiffGroupsAndTags=1) @danny.lan",
      "time": "11:40",
      "timestamp": "1726512027.180189",
      "is_reply": false
    },
    {
      "sender": "danny.lan",
      "user_id": "U03R26W3CDU",
      "message": "interesting, it failed 1/4 runs in the `afterAll` logic so it looks flaky, the `PUT extracted_fields` call failed after deleting a field with `Field missing. '84739'`.\n\nEven though we fail to save `extracted_fields` it doesn’t necessarily seem to be a “bug” since no error is shown to the user and we can still use the old `extracted_fields` which just has some extra data in it now.",
      "time": "12:18",
      "timestamp": "1726514286.963879",
      "is_reply": true
    },
    {
      "sender": "Serena",
      "user_id": "U01CZ3LBFU4",
      "message": "hmm should we intercept the `PUT extracted_fields` call or do something else so that Cypress doesn’t think that this counts as a test failure?",
      "time": "15:39",
      "timestamp": "1726526358.694369",
      "is_reply": true
    }
  ],
  "metadata": {
    "channel_id": "CSY11CK7T",
    "channel_name": "discuss-frontend",
    "date_file": "2024-09-16.json",
    "message_count": 3,
    "start_time": "1726512027.180189",
    "end_time": "1726526358.694369",
    "is_thread": true
  }
}