{
  "id": "ch_C06FA6A23_2019-07-26_1564157226.081900_thread",
  "type": "channel",
  "channel_name": "discuss-engineering",
  "conversation_type": "thread",
  "participants": [
    "Eric Han",
    "Aaron Vontell",
    "dlluncor",
    "Jonathan Shih"
  ],
  "messages": [
    {
      "sender": "Aaron Vontell",
      "user_id": "UCWNLU6CB",
      "message": "I am still seeing these errors in master, posted this a few times before, has there been a fix yet?\n```\ninstabase/handler/views/apps/shared/diff_util.py:367: error: Argument 1 to \"unified_diff\" has incompatible type \"List[unicode]\"; expected \"Sequence[str]\"\ninstabase/handler/views/apps/shared/diff_util.py:367: error: Argument 2 to \"unified_diff\" has incompatible type \"List[unicode]\"; expected \"Sequence[str]\"\ninstabase/handler/views/apps/shared/diff_util.py:367: error: Argument 3 to \"unified_diff\" has incompatible type \"unicode\"; expected \"str\"\ninstabase/handler/views/apps/shared/diff_util.py:367: error: Argument 4 to \"unified_diff\" has incompatible type \"unicode\"; expected \"str\"\ninstabase/handler/views/apps/shared/flow_util.py:767: error: Incompatible types in assignment (expression has type \"unicode\", variable has type \"ZipFile\")\ninstabase/handler/views/apps/shared/flow_util.py:789: error: Incompatible types in assignment (expression has type \"unicode\", variable has type \"ZipFile\")\ninstabase/handler/views/apps/shared/flow_util.py:815: error: Incompatible types in assignment (expression has type \"unicode\", variable has type \"ZipFile\")\n```",
      "time": "09:07",
      "timestamp": "1564157226.081900",
      "is_reply": false
    },
    {
      "sender": "dlluncor",
      "user_id": "U3UA06MFD",
      "message": "@Jonathan Shih @Eric Han you could help address the types thanks!",
      "time": "09:40",
      "timestamp": "1564159238.083400",
      "is_reply": true
    },
    {
      "sender": "Eric Han",
      "user_id": "UKPHNU5QE",
      "message": "I merged the fix for diff on master",
      "time": "11:57",
      "timestamp": "1564167438.087500",
      "is_reply": true
    },
    {
      "sender": "Jonathan Shih",
      "user_id": "UGJD45BCP",
      "message": "@Aaron Vontell @dlluncor how do i see these errors? apparently i can’t run mypy on webserver/shared-apps?",
      "time": "12:18",
      "timestamp": "1564168696.091000",
      "is_reply": true
    },
    {
      "sender": "Jonathan Shih",
      "user_id": "UGJD45BCP",
      "message": "nvm i figured out what’s wrong haha",
      "time": "12:25",
      "timestamp": "1564169148.091200",
      "is_reply": true
    }
  ],
  "metadata": {
    "channel_id": "C06FA6A23",
    "channel_name": "discuss-engineering",
    "date_file": "2019-07-26.json",
    "message_count": 5,
    "start_time": "1564157226.081900",
    "end_time": "1564169148.091200",
    "is_thread": true
  }
}