{
  "id": "ch_C06FA6A23_2025-03-27_1743112535.247609_thread",
  "type": "channel",
  "channel_name": "discuss-engineering",
  "conversation_type": "thread",
  "participants": [
    "Cody Boggs",
    "Nikolaos Kofinas"
  ],
  "messages": [
    {
      "sender": "Nikolaos Kofinas",
      "user_id": "U03DWCUEBHT",
      "message": "CI fails in two of my prs with this error:\n```\n[2025-03-27T21:13:47.196Z]       from . import pkg_resources\n\n[2025-03-27T21:13:47.196Z]     File \"/shared/venvs/api-server-OqbBKx_a-py3.9/lib/python3.9/site-packages/pip/_internal/metadata/pkg_resources.py\", line 8, in <module>\n\n[2025-03-27T21:13:47.196Z]       from pip._vendor import pkg_resources\n\n[2025-03-27T21:13:47.196Z]     File \"/shared/venvs/api-server-OqbBKx_a-py3.9/lib/python3.9/site-packages/pip/_vendor/pkg_resources/__init__.py\", line 3324, in <module>\n\n[2025-03-27T21:13:47.196Z]       def _initialize_master_working_set():\n\n[2025-03-27T21:13:47.196Z]     File \"/shared/venvs/api-server-OqbBKx_a-py3.9/lib/python3.9/site-packages/pip/_vendor/pkg_resources/__init__.py\", line 3298, in _call_aside\n\n[2025-03-27T21:13:47.196Z]       f(*args, **kwargs)\n\n[2025-03-27T21:13:47.196Z]     File \"/shared/venvs/api-server-OqbBKx_a-py3.9/lib/python3.9/site-packages/pip/_vendor/pkg_resources/__init__.py\", line 3356, in _initialize_master_working_set\n\n[2025-03-27T21:13:47.196Z]       list(map(working_set.add_entry, sys.path))\n\n[2025-03-27T21:13:47.196Z]     File \"/shared/venvs/api-server-OqbBKx_a-py3.9/lib/python3.9/site-packages/pip/_vendor/pkg_resources/__init__.py\", line 669, in add_entry\n\n[2025-03-27T21:13:47.196Z]       for dist in find_distributions(entry, True):\n\n[2025-03-27T21:13:47.196Z]     File \"/shared/venvs/api-server-OqbBKx_a-py3.9/lib/python3.9/site-packages/pip/_vendor/pkg_resources/__init__.py\", line 2133, in find_on_path\n\n[2025-03-27T21:13:47.196Z]       for dist in factory(fullpath):\n\n[2025-03-27T21:13:47.196Z]     File \"/shared/venvs/api-server-OqbBKx_a-py3.9/lib/python3.9/site-packages/pip/_vendor/pkg_resources/__init__.py\", line 2191, in distributions_from_metadata\n\n[2025-03-27T21:13:47.196Z]       if len(os.listdir(path)) == 0:\n\n[2025-03-27T21:13:47.196Z]   FileNotFoundError: [Errno 2] No such file or directory: '/shared/venvs/api-server-OqbBKx_a-py3.9/lib/python3.9/site-packages/cachetools-5.5.0.dist-info'```\nis something broken?",
      "time": "14:55",
      "timestamp": "1743112535.247609",
      "is_reply": false
    },
    {
      "sender": "Cody Boggs",
      "user_id": "U037PKN4USZ",
      "message": "@Nikolaos Kofinas can you link the jobs for me?",
      "time": "14:58",
      "timestamp": "1743112685.638159",
      "is_reply": true
    },
    {
      "sender": "Nikolaos Kofinas",
      "user_id": "U03DWCUEBHT",
      "message": "https://jenkins.instabase.com/blue/organizations/jenkins/instabase/detail/PR-69254/1/pipeline/\nhttps://jenkins.instabase.com/blue/organizations/jenkins/instabase/detail/PR-69258/3/pipeline/#step-43-log-362",
      "time": "14:58",
      "timestamp": "1743112707.556219",
      "is_reply": true
    },
    {
      "sender": "Nikolaos Kofinas",
      "user_id": "U03DWCUEBHT",
      "message": "anything out of the ordinary?",
      "time": "15:54",
      "timestamp": "1743116045.043909",
      "is_reply": true
    },
    {
      "sender": "Cody Boggs",
      "user_id": "U037PKN4USZ",
      "message": "Oh shoot sorry! I got my blinders on and promptly forgot to check :man-facepalming::skin-tone-3: Looking!",
      "time": "16:07",
      "timestamp": "1743116862.607359",
      "is_reply": true
    },
    {
      "sender": "Nikolaos Kofinas",
      "user_id": "U03DWCUEBHT",
      "message": "one of them passed with a rerun",
      "time": "16:08",
      "timestamp": "1743116890.121349",
      "is_reply": true
    },
    {
      "sender": "Cody Boggs",
      "user_id": "U037PKN4USZ",
      "message": "Hm, I don't see anything jumping out at me from a jenkins perspective, as far as stuck builders or network issues. I wonder if the failing runs were getting stomped on by some manner of shared dep cleanup or race condition",
      "time": "16:11",
      "timestamp": "1743117082.703249",
      "is_reply": true
    },
    {
      "sender": "Cody Boggs",
      "user_id": "U037PKN4USZ",
      "message": "Hopefully the rerun on the other PR passes as well, I'm not sure what would cause this to be a transient failure though. :thinking_face:\n\nI need to drop for tonight, but I'll check back in the AM",
      "time": "16:12",
      "timestamp": "1743117160.325849",
      "is_reply": true
    },
    {
      "sender": "Nikolaos Kofinas",
      "user_id": "U03DWCUEBHT",
      "message": "thank you, I will report back, have a good night",
      "time": "16:13",
      "timestamp": "1743117185.439859",
      "is_reply": true
    }
  ],
  "metadata": {
    "channel_id": "C06FA6A23",
    "channel_name": "discuss-engineering",
    "date_file": "2025-03-27.json",
    "message_count": 9,
    "start_time": "1743112535.247609",
    "end_time": "1743117185.439859",
    "is_thread": true
  }
}